/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile mobile = new Mobile();
        mobile.setName("Android");
        mobile.call("kjjjjjjjjjjj");
        mobile.PrintInfo();

        Android android = new Android();
        android.call("kkk");
    }
}
